require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'